version: '3.7'

services:
  nginx:
    image: nginx:stable
    ports:
      - 80
    networks:
      - test-takes-api
    volumes:
      - ./docker/nginx/sites.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    expose:
      - 9000
    networks:
      - test-takes-api
    volumes:
      - ./:/var/www/test-takers-api:ro

networks:
  test-takes-api:
    driver: bridge
